import {MenuItem, MenuType} from "../../../shared/models/menu-item";

export const menuList: MenuItem[] = [
    {
        'name': '首页',
        'permit': 'dashboard',
        'cached': false,
        'icon': 'home',
        'enabled': true,
        'url': 'dashboard',
        'target': '_self',
        'type': MenuType.PAGE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': []
    },
    {
        'name': '订单管理',
        'permit': 'order_module',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '',
        'target': '_self',
        'type': MenuType.MODULE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': [
            {
                'name': '查看',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '添加',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/add',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '搜索',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/search',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '草拟订单',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/draft-orders',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '装运',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/shipments',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '物流单号',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/tracking-numbers',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '礼品券',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/gift-certificates',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '订单状态',
                'permit': 'order:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/orders/order-statuses',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            }
        ]
    },
    {
        'name': '商品管理',
        'permit': 'product_module',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '',
        'target': '_self',
        'type': MenuType.MODULE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': [
            {
                'name': '全部商品',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/products',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '商品分类',
                'permit': 'category:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/categories',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '品牌管理',
                'permit': 'brand:read',
                'cached': false,
                'icon': '', 'enabled': true,
                'url': '/brands',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
        ]
    },
    {
        'name': '客户管理',
        'permit': 'product_module',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '',
        'target': '_self',
        'type': MenuType.MODULE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': [
            {
                'name': '查看',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/customers',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '添加',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/customers/add',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '搜索',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/customers/search',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '导入',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/customers/import',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '导出',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/customers/export',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '客户组',
                'permit': 'product:read',
                'cached': false,
                'icon': '',
                'enabled': true,
                'url': '/customers/groups',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
        ]
    },
    {
        'name': '系统管理',
        'permit': 'system_module',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '',
        'target': '_self',
        'type': MenuType.MODULE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': [
            {
                'name': '系统设置',
                'permit': 'role:read',
                'cached': false,
                'icon': '', 'enabled': true,
                'url': '/settings',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '角色管理',
                'permit': 'role:read',
                'cached': false,
                'icon': '', 'enabled': true,
                'url': '/settings/roles',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            },
            {
                'name': '用户管理',
                'permit': 'user:read',
                'cached': false,
                'icon': '', 'enabled': true,
                'url': '/settings/users',
                'target': '_self',
                'type': MenuType.PAGE,
                'displayOrder': 100,
                'isShownInMenu': true,
                'children': []
            }
        ]
    },
    {
        'name': '餐桌管理',
        'permit': 'diningtable:read',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '/dining-tables',
        'target': '_self',
        'type': MenuType.PAGE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': []
    },
    {
        'name': '外卖管理',
        'permit': 'takeout:read',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '/takeout/index',
        'target': '_self',
        'type': MenuType.PAGE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': []
    },
    {
        'name': '预订管理',
        'permit': 'reservation:read',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '/reservation/index',
        'target': '_self',
        'type': MenuType.PAGE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': []
    },
    {
        'name': '我的个人信息',
        'permit': 'reservation:read',
        'cached': false,
        'icon': 'home', 'enabled': true,
        'url': '/myprofile',
        'target': '_self',
        'type': MenuType.PAGE,
        'displayOrder': 100,
        'isShownInMenu': true,
        'children': []
    },
];
